In [5]:
# Cargar librerias
import pandas as pd
import numpy as np
import plotly.express as px

import plotly.io as pio 
pio.templates.default = "plotly"

In [6]:
# Cargar dataset
df = pd.read_csv(r"C:\Users\GTX 1660Ti\Downloads\Proyecto_S_7\vehicles_us.csv")
df["type"] = df["type"].astype(str)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  str
 3   condition     51525 non-null  str
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  str
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  str
 8   type          51525 non-null  str
 9   paint_color   42258 non-null  str
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  str
 12  days_listed   51525 non-null  int64
dtypes: float64(4), int64(2), str(7)
memory usage: 7.7 MB

In [8]:
df.sample(10)

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
4175,7800,2011.0,chevrolet silverado 1500,excellent,6.0,gas,196000.0,automatic,truck,silver,NaN,2018-12-22,42
30692,28995,NaN,ford f-150,like new,8.0,gas,40307.0,automatic,truck,white,1.0,2018-06-08,34
45116,15900,2014.0,dodge grand caravan,excellent,6.0,gas,43236.0,automatic,SUV,blue,NaN,2018-11-06,68
14148,11950,2014.0,ford mustang,like new,6.0,gas,71558.0,manual,coupe,red,NaN,2018-08-29,48
33590,15000,2005.0,jeep wrangler unlimited,excellent,6.0,gas,70000.0,manual,SUV,blue,1.0,2019-01-11,27
27520,4995,2007.0,nissan murano,good,6.0,gas,168076.0,automatic,wagon,silver,NaN,2018-12-23,95
45779,2599,2015.0,nissan rogue,like new,4.0,gas,66774.0,automatic,SUV,white,1.0,2018-06-09,64
26028,27665,2016.0,ford f-150,excellent,6.0,gas,65957.0,automatic,truck,NaN,1.0,2018-06-28,62
48124,5999,2000.0,honda accord,excellent,6.0,gas,44805.0,automatic,coupe,black,NaN,2018-09-21,108
25278,3425,2010.0,subaru forester,excellent,4.0,gas,172500.0,automatic,SUV,blue,1.0,2019-04-14,82

In [9]:
df.describe().round(1)

          price  model_year  cylinders  odometer   is_4wd  days_listed
count   51525.0     47906.0    46265.0   43633.0  25572.0      51525.0
mean    12132.5      2009.8        6.1  115553.5      1.0         39.6
std     10040.8         6.3        1.7   65094.6      0.0         28.2
min         1.0      1908.0        3.0       0.0      1.0          0.0
25%      5000.0      2006.0        4.0   70000.0      1.0         19.0
50%      9000.0      2011.0        6.0  113000.0      1.0         33.0
75%     16839.0      2014.0        8.0  155000.0      1.0         53.0
max    375000.0      2019.0       12.0  990000.0      1.0        271.0

In [10]:
# Seleccionar solo variables numéricas para poder calcular estadísticas
opciones = df.select_dtypes(include=np.number).columns.tolist()

In [11]:
# Elegir 2 variables cualquiera (por ejemplo, las dos primeras: price y model_year)
v = (opciones[0], opciones[1])

In [ ]:
# Filtrar nulos en esas dos columnas para evitar errores de cálculo
df_clean = df.dropna(subset=list(v))

# Visualizar histograma de variable 1
hist_plot01 = px.histogram(
    df_clean, 
    x = v[0], 
    title = f"Distribución {v[0]}", 
    color = "type", 
    #marginal = "box", 
    width = 700, 
    height = 400
)
hist_plot01.show()

In [13]:
# Calcular estadisticos de variable 1
prom1 = np.mean(df_clean[v[0]])
med1 = np.median(df_clean[v[0]])
desv1 = np.std(df_clean[v[0]])
print("Media: {:.1f}".format(prom1))
print("Mediana: {:.1f}".format(med1))
print("Desviación: {:.1f}".format(desv1))

Media: 12160.5
Mediana: 9000.0
Desviación: 10082.3

In [14]:
# Visualizar histograma de variable 2
hist_plot02 = px.histogram(
    df_clean, 
    x = v[1], 
    title = f"Distribución {v[1]}", 
    color = "type", 
    marginal = "box", 
    width = 700, 
    height = 400
)
hist_plot02.show()

In [15]:
# Calcular estadisticos de variable 2
prom2 = np.mean(df_clean[v[1]])
med2 = np.median(df_clean[v[1]])
desv2 = np.std(df_clean[v[1]])
print("Media: {:.1f}".format(prom2))
print("Mediana: {:.1f}".format(med2))
print("Desviación: {:.1f}".format(desv2))

Media: 2009.8
Mediana: 2011.0
Desviación: 6.3

In [16]:
# Visualizar dispersion entre variables
disp_plot = px.scatter(
    df_clean, 
    x = v[0], 
    y = v[1], 
    color = "type", 
    title = f"Dispersión {v[1]} vs. {v[0]}", 
    width = 700, 
    height = 400
)
disp_plot.show()

In [17]:
# Calcular correlacion entre variables
correl = np.corrcoef(df_clean[v[0]], df_clean[v[1]])
print("Correlación de Pearson: {:.1%}".format(correl[0,1]))

Correlación de Pearson: 42.9%